### ISSUE TITLE
Don't get injection on manually instantiated instance

### ISSUE THREAD

**Issue by deap82** [devaur/aurelia-property-injection#12]
I get the property injection to work on a class (component) instantiated by Aurelia.
But when I try it on a class I'm instantiating myself I get no injection, my "router" property stays undefined:

```
import { Router } from 'aurelia-router';
import { autoinject } from 'aurelia-property-injection';

export function create(data) {
    return new ResultsIndexClientModel(data);
}

class ResultsIndexClientModel {
    selectedSchoolId: number;

    @autoinject
    router: Router;

    constructor(public data) { }

    schoolIdChanged() {
        console.log('router: ' + this.router); //router is undefined here
    }
}
```

The schoolIdChanged method is called from markup through a change.bind. That markup has been "aurelia enhanced" as described here: 
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/8

**Comment by levan-g** [comment]
@deap82 it's impossible to get any kind of injection with directly instantiated class. You should use container to get injection work properly.

**Comment by deap82** [comment]
Yeah, I kind of guessed that but I haven't been able to figure out how to set up my own classes with the DI container, especially for this case where I need to initiate the instance with some data. I found a work around though, so currently I'm not using this plugin.
