### ISSUE TITLE
Bundling fails with Aurelia RC

### ISSUE THREAD

**Issue by RomkeVdMeulen** [devaur/aurelia-property-injection#5]
I'm trying to upgrade to Aurelia RC, but I can't get the bundle working.

```
Error on fetch for aurelia-dependency-injection.js at file://myproject/aurelia-dependency-injection.js
        Loading github:heruan/aurelia-property-injection@0.2.3/dist/invocation-handler-wrapper.js
        Loading github:heruan/aurelia-property-injection@0.2.3/dist/index.js
        Loading github:heruan/aurelia-property-injection@0.2.3.js
        Error: ENOENT: no such file or directory, open 'myproject/aurelia-dependency-injection.js'
    at Error (native)
```

**Comment by heruan** [comment]
Thank you @RomkeVdMeulen I'm updating dependencies right now for Aurelia RC.

**Comment by RomkeVdMeulen** [comment]
You might also want to look at the d.ts files that are generated: they don't declare the `aurelia-property-injection` module anymore. I patched the bundling for now by explicitly installing the dependencies, but now my typescript compiler is giving errors because of that.

**Comment by heruan** [comment]
That is the correct way to publish `.d.ts` files, see:

- https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/
- http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/

**Comment by RomkeVdMeulen** [comment]
I'm confused. How should I install the plugin so that the typescript compiler doesn't complain? The project doesn't contain a `typings.json`, so I can't add `"aurelia-property-injection": "github:heruan/aurelia-property-injection"` to my `typings.json` like I'm doing for the other Aurelia modules.

**Comment by heruan** [comment]
The next release will contain the `typings.json`, which is necessary with JSPM. Otherwise installing with NPM (`npm install github:heruan/aurelia-property-injection`) it should't be necessary. I'm pushing 0.3.0 in half an hour.

**Comment by RomkeVdMeulen** [comment]
Ah right. Thanks!

**Comment by heruan** [comment]
0.3.0 just released, all tests pass. Do you still experience your issue?

**Comment by RomkeVdMeulen** [comment]
Seems you have a spelling error in `typings.json`: `mail -> main`.

**Comment by heruan** [comment]
Fixed, thanks.

**Comment by RomkeVdMeulen** [comment]
I'm getting a warning when I try to re-install with JSPM:

```
# jspm install aurelia-property-injection=github:heruan/aurelia-property-injection
     Looking up github:heruan/aurelia-property-injection
     Updating registry cache...
     Downloading github:heruan/aurelia-property-injection@0.3.1

warn github:heruan/aurelia-property-injection@0.3.1 dependency installs skipped as it's a GitHub package with no registry property set.
     If the dependencies aren't needed ignore this message. Alternatively set a registry or dependencies override or use the npm registry version at jspm install npm:aurelia-property-injection@^0.3.1 instead.

ok   Installed aurelia-property-injection as github:heruan/aurelia-property-injection@^0.3.1 (0.3.1)
     Clearing configuration for github:heruan/aurelia-property-injection@0.2.3
ok   Install tree has no forks.

ok   Install complete.
```

Trying to install with JSPM over NPM doesn't work:
```
#jspm install npm:aurelia-property-injection
     Looking up npm:aurelia-property-injection
     Updating registry cache...
     Downloading npm:aurelia-property-injection@0.3.1

warn Error on processPackageConfig
     Package.json dependency aurelia-dependency-injection set to github:aurelia/dependency-injection@^0.9.2, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

warn Error processing package config for npm:aurelia-property-injection.

err  Error processing package config for npm:aurelia-property-injection.

warn Installation changes not saved.
```

**Comment by RomkeVdMeulen** [comment]
Ah, never mind: stale `config.js`.

**Comment by RomkeVdMeulen** [comment]
Hmm, still getting an error during bundling:

```
Error on fetch for aurelia-dependency-injection.js at file://myproject/aurelia-dependency-injection.js
        Loading github:heruan/aurelia-property-injection@0.3.1/dist/invocation-handler-wrapper.js
        Loading github:heruan/aurelia-property-injection@0.3.1/dist/index.js
        Loading github:heruan/aurelia-property-injection@0.3.1.js
        Error: ENOENT: no such file or directory, open 'myproject/aurelia-dependency-injection.js'
    at Error (native)
```

**Comment by RomkeVdMeulen** [comment]
Looking at the `config.js` generated by JSPM, there's a mapping

```
"aurelia-property-injection": "github:heruan/aurelia-property-injection@0.3.1"
```

but no mappings for the dependencies.

**Comment by RomkeVdMeulen** [comment]
If I manually add

```
"github:heruan/aurelia-property-injection@0.3.1": {
  "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-rc.1.0.0",
  "aurelia-metadata": "npm:aurelia-metadata@1.0.0-rc.1.0.0"
}
``` to the mappings in my `config.js` then bundling works.

**Comment by RomkeVdMeulen** [comment]
I see you've changed the install instructions to NPM. Is JSPM still going to be supported?

**Comment by matjaz** [comment]
PR is more than welcome. 👍

**Comment by heruan** [comment]
@RomkeVdMeulen JSPM is definitely being supported. Indeed, you can simply do
```shell
jspm install aurelia-property-injection
```
since the JSPM registry has an entry pointing to this repository.

**Comment by RomkeVdMeulen** [comment]
Hmm, if I execute that command I get a warning:

```
warn github:devaur/aurelia-property-injection@0.4.0 dependency installs skipped as it's a GitHub package with no registry property set.
     If the dependencies aren't needed ignore this message. Alternatively set a registry or dependencies override or use the npm registry version at jspm install npm:aurelia-property-injection@^0.4.0 instead.
```

If I execute `jspm install npm:aurelia-property-injection` everything installs properly.

**Comment by heruan** [comment]
The PR on the JSPM registry isn't merged yet. It will reference the NPM package and then you should be able to install without specifying the registry! I'm closing this since there's nothing left to do. Thank you for your testing!
